config/routes.rb
Rails.application.routes.draw do
  resources :professors
  resources :students
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/college.rb
class College < ApplicationRecord
  belongs_to :university
  has_one :dean
  has_many :departments
  validates :name, presence: { message: "El nombre del colegio no puede ser vacio"}
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :department
  has_many :sections
  validates :difficulty, numericality: { greater_than: 5, less_than: 11 }
end

app/models/dean.rb
class Dean < ApplicationRecord
  belongs_to :college
  validates :salary, numericality: { greater_than: 500 }
end

app/models/department.rb
class Department < ApplicationRecord
  belongs_to :college
  belongs_to :chair_professor, class_name: "Professor", foreign_key: "professor_id", optional: true
  has_many :professors
  has_many :courses
  has_many :students
  validates :description, length: { maximum: 2000 }
end

app/models/professor.rb
class Professor < ApplicationRecord
  has_many :sections
  has_one :chaired, class_name: "Department"
  belongs_to :department
  validates :salary, presence: true, numericality: { greater_than: 0, less_than: 1 }  
  validate :is_chavorruco_and_buena_onda

  def is_chavorruco_and_buena_onda
    if is_chavorruco && !buena_onda
      errors.add(:is_chavorruco, "Tienes que ser buena onda para ser chavorruco")
    end
  end
end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :course
  belongs_to :professor
  validate :not_repollo
  has_and_belongs_to_many :students
  def not_repollo
    if description.include?("repollo")
      errors.add(:description, "No puedes poner repollo")
    end
  end
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :department
  validate :not_hufflepuff
  has_and_belongs_to_many :sections
  def not_hufflepuff
    if (house == "Hufflepuff")
       errors.add(:house, "We dont accept Hufflepuff")
    end
  end
end

app/models/university.rb
class University < ApplicationRecord
  has_many :colleges
  validates :postal_code, length: { is: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/professors_controller.rb
class ProfessorsController < ApplicationController
  before_action :set_professor, only: %i[show edit destroy update]
  def index
    @professors = Professor.all
  end

  def new
    @professor = Professor.new
  end

  def show
  end

  def edit
  end

  def create
    @professor = Professor.new(professor_params)
    if @professor.save
      redirect_to @professor
    else
      puts @professor.errors.full_messages
      render 'new'
    end
  end

  def update
    if @professor.update(professor_params)
      redirect_to @professor
    else
      render 'edit'
    end
  end

  def destroy
    @professor.destroy
    redirect_to professors_path
  end

  private

  def set_professor
    @professor = Professor.find(params[:id])
  end

  def professor_params
    params.require(:professor).permit(:names, :surnames, :salary,
                                      :academic_degree, :buena_onda,
                                      :is_chavorruco, :department_id)

  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: %i[show edit destroy update]
  def index
    @students = Student.all
  end

  def new
    @student = Student.new
  end

  def show
  end

  def edit
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      redirect_to @student
    else
      render 'new'
    end
  end

  def update
    if @student.update(student_params)
      redirect_to @student
    else
      render 'edit'
    end
  end

  def destroy
    @student.destroy
    redirect_to students_path
  end

  private

  def set_student
    @student = Student.find(params[:id])
  end

  def student_params
    params.require(:student).permit(:names, :surnames, :enrollment, :house,
                                    :department_id)

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/professors_helper.rb
module ProfessorsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HogwartsApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/professors/_professor_fields.html.erb
<%= form_for @professor do |f| %>
  <%= f.label :names, "Nombres" %><br>
  <%= f.text_field :names %><br><br>
  <%= f.label :surnames, "Apellidos" %><br>
  <%= f.text_field :surnames %><br><br>
  <%= f.label :salary, "Salario" %><br>
  <%= f.number_field :salary, step: :any %><br><br>
  <%= f.label :academic_degree, "Academic Degree" %><br>
  <%= f.text_field :academic_degree %><br><br>
  <%= f.label :buena_onda, "Es buena onda?" %><br>
  <%= f.check_box :buena_onda %><br><br>
  <%= f.label :is_chavorruco, "Es chavorruco?" %><br>
  <%= f.check_box :is_chavorruco %><br><br>
  <%= f.hidden_field :department_id, value: 1 %>
  <%= f.submit submit_message %>
<% end %>

app/views/professors/edit.html.erb
<h1>Editar Profesor</h1>
<%= render 'professor_fields', submit_message: "Actualizar profesor" %>
<%= link_to "Regresar", professor_path(@professor) %>

app/views/professors/index.html.erb
<h1>Profesores</h1>
<% @professors.each do |professor| %>
  <%= link_to "#{professor.names} #{professor.surnames}", professor_path(professor) %>
  <li>Salario: <%= professor.salary %></li>
  <li>Academic Degree: <%= professor.academic_degree %></li>
  <li>Buena Onda: <%= (professor.buena_onda ? "Si" : "No") %></li>
  <li>Chavorruco: <%= (professor.is_chavorruco ? "Si" : "No") %></li>
<% end %>

<%= link_to "Nuevo Profesor", new_professor_path %>

app/views/professors/new.html.erb
<h1>Nuevo Profesor</h1>
<%= render 'professor_fields', submit_message: "Crear profesor" %>
<%= link_to "Regresar", professors_path %>

app/views/professors/show.html.erb
<h1>Profesor</h1>
<h2>Nombres: </h2>
<p><%= @professor.names %></p>

<h2>Apellidos: </h2>
<p><%= @professor.surnames %></p>

<h2>Salario: </h2>
<p><%= @professor.salary %></p>

<h2>Academic Degree: </h2>
<p><%= @professor.academic_degree %></p>

<h2>Buena onda: </h2>
<p><%= (@professor.buena_onda ? "Si" : "No")%></p>

<h2>Chavorruco: </h2>
<p><%= (@professor.is_chavorruco ? "Si" : "No")%></p>

<%= link_to "Regresar", professors_path %>
<%= link_to "Editar", edit_professor_path(@professor) %>
<%= link_to "Eliminiar", professor_path(@professor), method: :delete %>

app/views/students/_student_fields.html.erb
<%= form_for @student do |f| %>
  <%= f.label :names, "Nombres" %><br>
  <%= f.text_field :names %><br><br>
  <%= f.label :surnames, "Apellidos" %><br>
  <%= f.text_field :surnames %><br><br>
  <%= f.label :enrollment, "Matricula" %><br>
  <%= f.text_field :enrollment %><br><br>
  <%= f.label :house, "Casa" %><br>
  <%= f.text_field :house %><br><br>
  <%= f.hidden_field :department_id, value: 1 %>
  <%= f.submit submit_message %>
<% end %>

app/views/students/edit.html.erb
<h1>Editar Estudiante</h1>
<%= render 'student_fields', submit_message: "Actualizar estudiante" %>
<%= link_to "Regresar", student_path(@student) %>

app/views/students/index.html.erb
<h1>Estudiantes</h1>
<% @students.each do |student| %>
  <%= link_to "#{student.names} #{student.surnames}", student_path(student) %>
  <li>Matricula: <%= student.enrollment %></li>
  <li>Casa: <%= student.house %></li>
<% end %>

<%= link_to "Nuevo Estudiante", new_student_path %>

app/views/students/new.html.erb
<h1>Crear Estudiante</h1>
<%= render 'student_fields', submit_message: "Crear Estudiante"%>

app/views/students/show.html.erb
<h1>Estudiante</h1>
<h2>Nombres: </h2>
<p><%= @student.names %></p>

<h2>Apellidos: </h2>
<p><%= @student.surnames %></p>

<h2>Matricula: </h2>
<p><%= @student.enrollment %></p>

<h2>Casa: </h2>
<p><%= @student.house %></p>

<%= link_to "Regresar", students_path %>
<%= link_to "Editar", edit_student_path(@student) %>
<%= link_to "Eliminiar", student_path(@student), method: :delete %>